algoritmo "soma_tres_numeros"
// Função :
// Autor : Julia Vitoria S.S
// Data : 13/04/2026
// Seção de Declarações 
var
  n1, n2, n3, soma: real

inicio
   escreva("Digite o valor do número um: ")
   leia(n1)
   
   escreva("Digite o valor do número dois: ")
   leia(n2)
   
   escreva("Digite o valor do número três: ")
   leia(n3)
   
   soma <- n1 + n2 + n3
   
   escreva("A soma dos três números foi: ", soma)
fimalgoritmo
